//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.07 at 03:24:41 AM EET 
//


package tariff;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TariffParameters complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TariffParameters">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="favNumber">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="[0]\d{9}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="tariffication">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="12sec"/>
 *               &lt;enumeration value="min"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="joinPrice">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TariffParameters", propOrder = {
    "favNumber",
    "tariffication",
    "joinPrice"
})
public class TariffParameters {

    @XmlElement(required = true)
    protected String favNumber;
    @XmlElement(required = true)
    protected String tariffication;
    protected int joinPrice;

    /**
     * Gets the value of the favNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFavNumber() {
        return favNumber;
    }

    /**
     * Sets the value of the favNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFavNumber(String value) {
        this.favNumber = value;
    }

    /**
     * Gets the value of the tariffication property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTariffication() {
        return tariffication;
    }

    /**
     * Sets the value of the tariffication property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTariffication(String value) {
        this.tariffication = value;
    }

    /**
     * Gets the value of the joinPrice property.
     * 
     */
    public int getJoinPrice() {
        return joinPrice;
    }

    /**
     * Sets the value of the joinPrice property.
     * 
     */
    public void setJoinPrice(int value) {
        this.joinPrice = value;
    }

}
